### ISSUE TITLE
panic on saveSessionTicket

### ISSUE THREAD

**Issue by RonaldinhoL** [refraction-networking/utls#218] opened 2023-08-10 06:40 UTC
i just update to latest version and my app crashed

```
func (hs *clientHandshakeState) saveSessionTicket() error {
	if hs.ticket == nil {
		return nil
	}
	c := hs.c

	cacheKey := c.clientSessionCacheKey()
	if cacheKey == "" {
		return nil
	}

	session, err := c.sessionState()
	if err != nil {
		return err
	}
	session.secret = hs.masterSecret

	cs := &ClientSessionState{ticket: hs.ticket, session: session}
	>>>>>    c.config.ClientSessionCache.Put(cacheKey, cs)
	return nil
}
```

line `c.config.ClientSessionCache.Put(cacheKey, cs)`  ClientSessionCache was nil

**Comment by gaukas** [comment] 2023-08-10 19:50
Hi @RonaldinhoL, 

Will you be able to provide further details on how does your application uses uTLS (especially how you configured your `UClient`/`UConn`). 

The panic was triggered in an unmodified part from our upstream, `crypto/tls`, so will it be possible for you to try connecting to the same server with `crypto/tls` from **Go 1.21.x** and see what happens, while trying your best replicating the configurations. AFAIK, Go 1.21 changed a lot in how session resumptions are handled, so breaking changes are actually expected. 

Please let me know so we could proceed investigating.

**Comment by gaukas** [comment] 2023-08-10 20:01
Some updates while waiting for your response: 

Seemingly all handshakes leading to a TLS 1.2 connection will fail, and it is not triggered in `utls.Client()` or `crypto/tls.Client()`, thus indeed a bug in our implementation.

**Comment by gaukas** [comment] 2023-08-10 20:27
So it turns out `crypto/tls` started actively saving session tickets now (seems it wasn't before). If your parrot advertises `session_ticket` extension and the server echoes it back, a session ticket will be received by your client AND it crashes when you don't have a `ClientSessionCache` set. 

A correct use of this new feature is, set a `ClientSessionCache` when you advertises `session_ticket` extension. While I don't see it as a clean fix since it breaks (again) the originality on `crypto/tls` parts, we could definitely push a fix to ignore saving to `ClientSessionCache` when it is nil.

**Comment by RonaldinhoL** [comment] 2023-08-11 04:49
> So it turns out `crypto/tls` started actively saving session tickets now (seems it wasn't before). If your parrot advertises `session_ticket` extension and the server echoes it back, a session ticket will be received by your client AND it crashes when you don't have a `ClientSessionCache` set.
> 
> A correct use of this new feature is, set a `ClientSessionCache` when you advertises `session_ticket` extension. While I don't see it as a clean fix since it breaks (again) the originality on `crypto/tls` parts, we could definitely push a fix to ignore saving to `ClientSessionCache` when it is nil.

i am using HelloChrome_106_Shuffle,  i realized there are two functions `func NewLRUClientSessionCache(capacity int) ClientSessionCache` and `func (uconn *UConn) SetSessionCache(cache ClientSessionCache)`, but not found xref to it except testcases, i am not familier enough with utls/tls so cann;t know what is the cause of it

**Comment by RonaldinhoL** [comment] 2023-08-11 05:09
```
conn.SetSessionCache(utls.NewLRUClientSessionCache(64))
```
this not work, will cause another panic

```
case *SessionTicketExtension:
			var cs *ClientSessionState
			if session == nil && uconn.config.ClientSessionCache != nil {
				cacheKey := uconn.clientSessionCacheKey()
				cs, _ = uconn.config.ClientSessionCache.Get(cacheKey)
				>>>>>   session = cs.session  <<<<<<< cs.session is nil
				// TODO: use uconn.loadSession(hello.getPrivateObj()) to support TLS 1.3 PSK-style resumption
			}
			err := uconn.SetSessionState(cs)
			if err != nil {
				return err
			}
```

**Comment by gaukas** [comment] 2023-08-11 05:10
The essential root cause is `crypto/tls` started to automatically saving any `session_ticket` received to `Config.ClientSessionCache`. So "the supposed way" to use this feature will be setting a proper `ClientSessionCache`.

**Comment by gaukas** [comment] 2023-08-11 05:11
> this not work, will cause another panic

It should be fixed in v1.4.1 by #214.

**Comment by gaukas** [comment] 2023-08-11 05:24
I pushed v1.4.2 as a fix to this, can you try it?

**Comment by RonaldinhoL** [comment] 2023-08-11 06:23
> I pushed v1.4.2 as a fix to this, can you try it?

yes working

**Closed** 2023-08-11 06:38 UTC
Labels: bug
